<?xml version="1.0" encoding="utf-8"?><Database Name="TEST" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=samsung;Initial Catalog=TEST;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TESTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Booking" Member="Bookings">
    <Type Name="Booking">
      <Column Name="BookingID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookingCode" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="ActualStartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ExpectedEndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="BookingDescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="BookingStatus" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Booking_Evaluation" Member="Evaluations" ThisKey="BookingID" OtherKey="BOOKID" Type="Evaluation" />
      <Association Name="Booking_ExeSecrataryAssign" Member="ExeSecrataryAssigns" ThisKey="BookingID" OtherKey="bookID" Type="ExeSecrataryAssign" />
      <Association Name="Booking_SupervisorAssign" Member="SupervisorAssigns" ThisKey="BookingID" OtherKey="bookID" Type="SupervisorAssign" />
    </Type>
  </Table>
  <Table Name="dbo.Butler" Member="Butlers">
    <Type Name="Butler">
      <Column Name="ButlerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ISAssigned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ServiceProvider_Butler" Member="ServiceProvider" ThisKey="ButlerID" OtherKey="ServiceProviderID" Type="ServiceProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Certificate" Member="Certificates">
    <Type Name="Certificate">
      <Column Name="CertificateType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CertificateDate" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CertificateImage" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Employee_Certificate" Member="Employee" ThisKey="EmployeeID" OtherKey="EID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Criteria" Member="Criterias">
    <Type Name="Criteria">
      <Column Name="CriteriaID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CriteriaName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CriteriaDescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CriteriaType" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CriteriaWeight" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="Criteria_Evaluation" Member="Evaluations" ThisKey="CriteriaID" OtherKey="CriID" Type="Evaluation" />
    </Type>
  </Table>
  <Table Name="dbo.Driver" Member="Drivers">
    <Type Name="Driver">
      <Column Name="DriverID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ISAssigned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ServiceProvider_Driver" Member="ServiceProvider" ThisKey="DriverID" OtherKey="ServiceProviderID" Type="ServiceProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeCode" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NationalID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeePassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeType" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="JobDescription" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Certificate" Member="Certificates" ThisKey="EID" OtherKey="EmployeeID" Type="Certificate" />
      <Association Name="Employee_ExeSecratary" Member="ExeSecratary" ThisKey="EID" OtherKey="ExeSID" Type="ExeSecratary" Cardinality="One" />
      <Association Name="Employee_Genmanager" Member="Genmanager" ThisKey="EID" OtherKey="GeneralManagerID" Type="Genmanager" Cardinality="One" />
      <Association Name="Employee_Supervisor" Member="Supervisor" ThisKey="EID" OtherKey="SupervisorID" Type="Supervisor" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Evaluation" Member="Evaluations">
    <Type Name="Evaluation">
      <Column Name="EvaluationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="WeightGiven" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Coment" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EXSECID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BOOKID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CriID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceProviderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Booking_Evaluation" Member="Booking" ThisKey="BOOKID" OtherKey="BookingID" Type="Booking" IsForeignKey="true" />
      <Association Name="Criteria_Evaluation" Member="Criteria" ThisKey="CriID" OtherKey="CriteriaID" Type="Criteria" IsForeignKey="true" />
      <Association Name="ExeSecratary_Evaluation" Member="ExeSecratary" ThisKey="EXSECID" OtherKey="ExeSID" Type="ExeSecratary" IsForeignKey="true" />
      <Association Name="ServiceProvider_Evaluation" Member="ServiceProvider" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="ServiceProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExeSecratary" Member="ExeSecrataries">
    <Type Name="ExeSecratary">
      <Column Name="ExeSID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ExeSecratary_Evaluation" Member="Evaluations" ThisKey="ExeSID" OtherKey="EXSECID" Type="Evaluation" />
      <Association Name="ExeSecratary_ExeSecrataryAssign" Member="ExeSecrataryAssigns" ThisKey="ExeSID" OtherKey="ExeSecrataryID" Type="ExeSecrataryAssign" />
      <Association Name="Employee_ExeSecratary" Member="Employee" ThisKey="ExeSID" OtherKey="EID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExeSecrataryAssign" Member="ExeSecrataryAssigns">
    <Type Name="ExeSecrataryAssign">
      <Column Name="DateOfAssignment" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ExeSecrataryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceProviderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="bookID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Booking_ExeSecrataryAssign" Member="Booking" ThisKey="bookID" OtherKey="BookingID" Type="Booking" IsForeignKey="true" />
      <Association Name="ExeSecratary_ExeSecrataryAssign" Member="ExeSecratary" ThisKey="ExeSecrataryID" OtherKey="ExeSID" Type="ExeSecratary" IsForeignKey="true" />
      <Association Name="ServiceB_ExeSecrataryAssign" Member="ServiceB" ThisKey="ServiceID" OtherKey="SerciveID" Type="ServiceB" IsForeignKey="true" />
      <Association Name="ServiceProvider_ExeSecrataryAssign" Member="ServiceProvider" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="ServiceProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Genmanager" Member="Genmanagers">
    <Type Name="Genmanager">
      <Column Name="GeneralManagerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Genmanager_Report" Member="Reports" ThisKey="GeneralManagerID" OtherKey="GeneralMID" Type="Report" />
      <Association Name="Employee_Genmanager" Member="Employee" ThisKey="GeneralManagerID" OtherKey="EID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Govermental" Member="Govermentals">
    <Type Name="Govermental">
      <Column Name="GovermentalID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ISAssigned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ServiceProvider_Govermental" Member="ServiceProvider" ThisKey="GovermentalID" OtherKey="ServiceProviderID" Type="ServiceProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Leave" Member="Leaves">
    <Type Name="Leave">
      <Column Name="LeaveID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeOfLeave" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="ReasonForLeave" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceProviderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ServiceProvider_Leave" Member="ServiceProvider" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="ServiceProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report" Member="Reports">
    <Type Name="Report">
      <Column Name="ReportID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReportDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ReportDescription" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="GeneralMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Genmanager_Report" Member="Genmanager" ThisKey="GeneralMID" OtherKey="GeneralManagerID" Type="Genmanager" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceB" Member="ServiceBs">
    <Type Name="ServiceB">
      <Column Name="SerciveID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceType" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceProviderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ServiceB_ExeSecrataryAssign" Member="ExeSecrataryAssigns" ThisKey="SerciveID" OtherKey="ServiceID" Type="ExeSecrataryAssign" />
      <Association Name="ServiceB_SupervisorAssign" Member="SupervisorAssigns" ThisKey="SerciveID" OtherKey="ServiceID" Type="SupervisorAssign" />
      <Association Name="ServiceProvider_ServiceB" Member="ServiceProvider" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="ServiceProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceProvider" Member="ServiceProviders">
    <Type Name="ServiceProvider">
      <Column Name="ServiceProviderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceProviderCode" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="SPFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SPLastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SPNationalID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="SpPhoneNumber" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SPDateOfBirth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SPEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SpPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceProviderAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ServiceProviderType" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="ServiceProvider_Butler" Member="Butler" ThisKey="ServiceProviderID" OtherKey="ButlerID" Type="Butler" Cardinality="One" />
      <Association Name="ServiceProvider_Driver" Member="Driver" ThisKey="ServiceProviderID" OtherKey="DriverID" Type="Driver" Cardinality="One" />
      <Association Name="ServiceProvider_Evaluation" Member="Evaluations" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="Evaluation" />
      <Association Name="ServiceProvider_ExeSecrataryAssign" Member="ExeSecrataryAssigns" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="ExeSecrataryAssign" />
      <Association Name="ServiceProvider_Govermental" Member="Govermental" ThisKey="ServiceProviderID" OtherKey="GovermentalID" Type="Govermental" Cardinality="One" />
      <Association Name="ServiceProvider_Leave" Member="Leaves" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="Leave" />
      <Association Name="ServiceProvider_ServiceB" Member="ServiceBs" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="ServiceB" />
      <Association Name="ServiceProvider_SupervisorAssign" Member="SupervisorAssigns" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="SupervisorAssign" />
    </Type>
  </Table>
  <Table Name="dbo.Supervisor" Member="Supervisors">
    <Type Name="Supervisor">
      <Column Name="SupervisorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Supervisor_SupervisorAssign" Member="SupervisorAssigns" ThisKey="SupervisorID" OtherKey="supervisorID" Type="SupervisorAssign" />
      <Association Name="Employee_Supervisor" Member="Employee" ThisKey="SupervisorID" OtherKey="EID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SupervisorAssign" Member="SupervisorAssigns">
    <Type Name="SupervisorAssign">
      <Column Name="DateOfAssignment" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="supervisorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceProviderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ServiceID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="bookID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Booking_SupervisorAssign" Member="Booking" ThisKey="bookID" OtherKey="BookingID" Type="Booking" IsForeignKey="true" />
      <Association Name="ServiceProvider_SupervisorAssign" Member="ServiceProvider" ThisKey="ServiceProviderID" OtherKey="ServiceProviderID" Type="ServiceProvider" IsForeignKey="true" />
      <Association Name="ServiceB_SupervisorAssign" Member="ServiceB" ThisKey="ServiceID" OtherKey="SerciveID" Type="ServiceB" IsForeignKey="true" />
      <Association Name="Supervisor_SupervisorAssign" Member="Supervisor" ThisKey="supervisorID" OtherKey="SupervisorID" Type="Supervisor" IsForeignKey="true" />
    </Type>
  </Table>
</Database>